-- ============================================================================
-- GearSync - TurtleLootLine Addon
-- Syncs equipped gear to desktop companion and displays upgrade recommendations
-- ============================================================================

-- Saved data (written to WTF folder)
GearSyncData = GearSyncData or {}

-- Upgrade data (generated by Electron companion)
GearSyncUpgrades = GearSyncUpgrades or {}

-- Slot IDs to slot names mapping
local SLOT_NAMES = {
    [1] = "Head",
    [2] = "Neck",
    [3] = "Shoulder",
    [4] = "Shirt",
    [5] = "Chest",
    [6] = "Waist",
    [7] = "Legs",
    [8] = "Feet",
    [9] = "Wrist",
    [10] = "Hands",
    [11] = "Finger1",
    [12] = "Finger2",
    [13] = "Trinket1",
    [14] = "Trinket2",
    [15] = "Back",
    [16] = "MainHand",
    [17] = "OffHand",
    [18] = "Ranged",
    [19] = "Tabard"
}

-- Create main event frame
local frame = CreateFrame("Frame")

-- ============================================================================
-- UTILITY FUNCTIONS
-- ============================================================================

local function Print(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cFF00FF00[GearSync]|r " .. msg)
end

local function PrintError(msg)
    DEFAULT_CHAT_FRAME:AddMessage("|cFFFF0000[GearSync]|r " .. msg)
end

-- ============================================================================
-- EQUIPMENT SCANNING
-- ============================================================================

-- Scan all equipped gear and return equipment table
local function ScanEquipment()
    local equipment = {}

    for slotId = 1, 19 do
        local itemLink = GetInventoryItemLink("player", slotId)

        if itemLink then
            local _, _, itemIdStr = string.find(itemLink, "item:(%d+)")
            local itemId = tonumber(itemIdStr)
            local itemName = GetItemInfo(itemLink)

            if itemId and itemName then
                equipment[slotId] = {
                    slot = SLOT_NAMES[slotId],
                    itemId = itemId,
                    itemName = itemName,
                    itemLink = itemLink
                }
            end
        end
    end

    return equipment
end

-- ============================================================================
-- DATA PERSISTENCE
-- ============================================================================

-- Save current gear data to SavedVariables
local function SaveData()
    local equipment = ScanEquipment()

    GearSyncData = {
        lastUpdated = time(),
        character = UnitName("player"),
        realm = GetRealmName(),
        class = UnitClass("player"),
        equipment = equipment
    }

    -- Debug: count equipped items
    local count = 0
    for _ in pairs(equipment) do
        count = count + 1
    end

    -- Print(string.format("Scanned %d equipped items", count))
end

-- ============================================================================
-- EVENT HANDLERS
-- ============================================================================

-- Main event handler
local function OnEvent(self, event, ...)
    if event == "PLAYER_ENTERING_WORLD" then
        -- Player logged in or entered world
        SaveData()
        Print("Gear scanned! Desktop companion will sync automatically.")

        -- Show upgrade count if available
        local upgradeCount = 0
        for _ in pairs(GearSyncUpgrades) do
            upgradeCount = upgradeCount + 1
        end

        if upgradeCount > 0 then
            Print(string.format("Loaded upgrade data for %d items", upgradeCount))
        end

    elseif event == "PLAYER_EQUIPMENT_CHANGED" then
        -- Equipment changed (equipped/unequipped item)
        local slot = arg1
        SaveData()
        -- Print(string.format("Equipment changed in slot: %s", SLOT_NAMES[slot] or slot))

    elseif event == "UNIT_INVENTORY_CHANGED" then
        -- Inventory changed
        local unit = arg1
        if unit == "player" then
            SaveData()
        end
    end
end

frame:SetScript("OnEvent", OnEvent)

-- Register events
frame:RegisterEvent("PLAYER_ENTERING_WORLD")
frame:RegisterEvent("PLAYER_EQUIPMENT_CHANGED")
frame:RegisterEvent("UNIT_INVENTORY_CHANGED")

-- ============================================================================
-- TOOLTIP HOOK FOR UPGRADE DISPLAY
-- ============================================================================

-- Get color code for stat change
local function GetStatColor(value)
    if not value then return "|cFFFFFFFF" end

    local str = tostring(value)
    if string.sub(str, 1, 1) == "+" then
        return "|cFF00FF00"  -- Green for positive
    elseif string.sub(str, 1, 1) == "-" then
        return "|cFFFF0000"  -- Red for negative
    else
        return "|cFFFFFFFF"  -- White for neutral
    end
end

-- Format stat name for display
local function FormatStatName(statKey)
    -- Convert camelCase to readable format
    local formatted = string.gsub(statKey, "([a-z])([A-Z])", "%1 %2")
    -- Capitalize first letter
    return string.upper(string.sub(formatted, 1, 1)) .. string.sub(formatted, 2)
end

-- Hook GameTooltip to show upgrade data
local function OnTooltipSetItem(tooltip)
    local _, itemLink = tooltip:GetItem()
    if not itemLink then return end

    -- Extract item ID from link
    local _, _, itemIdStr = string.find(itemLink, "item:(%d+)")
    if not itemIdStr then return end

    local itemId = tonumber(itemIdStr)
    if not itemId then return end

    -- Check if we have upgrade data for this item
    local upgrade = GearSyncUpgrades[itemId]
    if not upgrade then return end

    -- Add separator
    tooltip:AddLine(" ")
    tooltip:AddLine("|cFF00BFFF⚔ TurtleLootLine:|r")

    -- Display stats in order: stamina, armor, strength, agility, etc., then overall
    local statsOrder = {
        "stamina", "armor", "strength", "agility", "intellect", "spirit",
        "defense", "attackPower", "spellPower", "healing", "hitRating",
        "critRating", "hasteRating", "dodgeRating", "parryRating", "blockRating"
    }

    for _, statKey in ipairs(statsOrder) do
        local value = upgrade[statKey]
        if value then
            local color = GetStatColor(value)
            local statName = FormatStatName(statKey)
            tooltip:AddLine("  " .. statName .. ": " .. color .. value .. "|r")
        end
    end

    -- Overall stat (highlighted in gold)
    if upgrade.overall then
        local color = GetStatColor(upgrade.overall)
        tooltip:AddLine("  |cFFFFD700Overall: " .. color .. upgrade.overall .. "|r")
    end

    -- Note (if available)
    if upgrade.note then
        tooltip:AddLine("  |cFFAAAAAA" .. upgrade.note .. "|r")
    end

    -- Refresh tooltip to update size
    tooltip:Show()
end

-- Hook both GameTooltip and ItemRefTooltip
GameTooltip:HookScript("OnTooltipSetItem", OnTooltipSetItem)
ItemRefTooltip:HookScript("OnTooltipSetItem", OnTooltipSetItem)

-- ============================================================================
-- SLASH COMMANDS
-- ============================================================================

local function HandleSlashCommand(msg)
    msg = string.lower(msg or "")

    if msg == "scan" or msg == "s" then
        SaveData()
        Print("Manual scan complete! Data saved.")

    elseif msg == "stats" or msg == "stat" then
        -- Show statistics
        local equipment = ScanEquipment()
        local equippedCount = 0
        for _ in pairs(equipment) do
            equippedCount = equippedCount + 1
        end

        local upgradeCount = 0
        for _ in pairs(GearSyncUpgrades) do
            upgradeCount = upgradeCount + 1
        end

        Print("--- Statistics ---")
        Print(string.format("Equipped items: %d", equippedCount))
        Print(string.format("Upgrade data loaded: %d items", upgradeCount))

        if GearSyncData.lastUpdated then
            local timeSince = time() - GearSyncData.lastUpdated
            Print(string.format("Last scan: %d seconds ago", timeSince))
        end

    elseif msg == "clear" then
        -- Clear saved data
        GearSyncData = {}
        Print("Saved data cleared")

    elseif msg == "upgrades" then
        -- List items with upgrade data
        Print("--- Items with Upgrade Data ---")
        local count = 0
        for itemId, data in pairs(GearSyncUpgrades) do
            count = count + 1
            local itemName = GetItemInfo(itemId) or "Unknown"
            local overall = data.overall or "N/A"
            Print(string.format("%s (%d): %s", itemName, itemId, overall))

            if count >= 10 then
                Print("... and more. Total: " .. count .. " items")
                break
            end
        end

        if count == 0 then
            Print("No upgrade data loaded")
        end

    elseif msg == "help" or msg == "h" or msg == "?" then
        Print("--- Commands ---")
        Print("/gs scan - Manually scan and save equipped gear")
        Print("/gs stats - Show addon statistics")
        Print("/gs upgrades - List items with upgrade data")
        Print("/gs clear - Clear saved data")
        Print("/gs help - Show this help")

    else
        Print("Unknown command. Type /gs help for available commands")
    end
end

-- Register slash commands
SLASH_GEARSYNC1 = "/gs"
SLASH_GEARSYNC2 = "/gearsync"
SlashCmdList["GEARSYNC"] = HandleSlashCommand

-- ============================================================================
-- INITIALIZATION
-- ============================================================================

Print("Loaded! Type /gs help for commands")
