-- Auto-generated by TurtleLootLine Companion
-- This file is automatically updated by the desktop companion app
-- Do not edit this file manually

-- Upgrade recommendations will be populated here by the companion app
-- Format: GearSyncUpgrades[itemId] = { stamina = "+15", armor = "+120", overall = "+8.5%", note = "BIS for Phase 2" }

GearSyncUpgrades = GearSyncUpgrades or {}

-- Example data (will be replaced by real data from companion app):
-- GearSyncUpgrades = {
--     [12640] = {
--         stamina = "+15",
--         armor = "+120",
--         defense = "-2",
--         overall = "+8.5%",
--         note = "BIS for Phase 2",
--     },
--     [11726] = {
--         stamina = "+8",
--         armor = "+80",
--         overall = "+3.2%",
--     },
-- }
